# Generated by Django 6.0.6 on 2026-08-17 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_keys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WidgetConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_name', models.CharField(default='AI Assistant', max_length=100)),
                ('welcome_message', models.CharField(default='Hi! How can I help you today?', max_length=500)),
                ('light_primary_color', models.CharField(default='#6366f1', help_text='Bubble + header background (hex or rgb)', max_length=20)),
                ('light_secondary_color', models.CharField(default='#ffffff', help_text='Chat window background (hex or rgb)', max_length=20)),
                ('dark_primary_color', models.CharField(default='#818cf8', help_text='Dark mode: bubble + header background', max_length=20)),
                ('dark_secondary_color', models.CharField(default='#1e1e2e', help_text='Dark mode: chat window background', max_length=20)),
                ('force_dark_mode', models.BooleanField(default=False, help_text='Always show in dark mode')),
                ('allow_user_toggle', models.BooleanField(default=True, help_text='Show light/dark toggle button in widget')),
                ('icon_url', models.URLField(blank=True, help_text='URL of custom icon image (Supabase)', null=True)),
                ('icon_emoji', models.CharField(default='💬', help_text='Fallback emoji if no custom icon', max_length=8)),
                ('position', models.CharField(choices=[('bottom-right', 'Bottom Right'), ('bottom-left', 'Bottom Left')], default='bottom-right', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_key', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='widget_config', to='api_keys.apikey')),
            ],
            options={
                'db_table': 'widget_configs',
            },
        ),
    ]
