# Generated by Django 6.0.6 on 2026-09-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_keys', '0002_widgetconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='document_ids',
            field=models.JSONField(blank=True, default=list, help_text='Documents linked to this key/widget'),
        ),
    ]
