# Generated by Django 6.0.6 on 2026-09-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_keys', '0003_apikey_document_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetconfig',
            name='system_prompt',
            field=models.TextField(blank=True, default='', help_text='Custom system instructions for the AI (set by owner in Knowledge Base)'),
        ),
        migrations.AlterField(
            model_name='widgetconfig',
            name='icon_url',
            field=models.TextField(blank=True, help_text='URL or data URI of custom icon image', null=True),
        ),
    ]
