# Generated by Django 6.0.6 on 2026-08-17 12:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('stripe_price_id', models.CharField(blank=True, help_text='Stripe Price ID e.g. price_xxx', max_length=100)),
                ('stripe_product_id', models.CharField(blank=True, max_length=100)),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('price_yearly', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('max_documents', models.IntegerField(default=3, help_text='Max documents per account (-1 = unlimited)')),
                ('max_api_keys', models.IntegerField(default=1, help_text='Max API keys (-1 = unlimited)')),
                ('max_requests_per_month', models.IntegerField(default=100, help_text='Max chat requests/month (-1 = unlimited)')),
                ('max_file_size_mb', models.IntegerField(default=5, help_text='Max file size in MB')),
                ('widget_customization', models.BooleanField(default=False)),
                ('priority_support', models.BooleanField(default=False)),
                ('custom_domain', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'billing_plans',
                'ordering': ['price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled'), ('past_due', 'Past Due'), ('trialing', 'Trialing'), ('incomplete', 'Incomplete')], default='active', max_length=20)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('requests_this_month', models.IntegerField(default=0)),
                ('requests_reset_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'billing_subscriptions',
            },
        ),
    ]
